---
#### 제로베이스(https://zero-base.co.kr/)
#### 데이터사이언스 90일 완주반 
---
#### **Guideline**
- 총점 100점으로 주차별로 약 2~3개 문제가 제시됩니다
- 각 문제마다 안내사항과 요구사항을 꼼꼼하게 확인해주신 후, 코드를 작성해주세요 
- 코드는 제시드리는 결과만 같게 나온다면, 추후 모범답안으로 드리는 코드와 달라도 괜찮습니다 

#### **Notice!** 
- 제출 기한을 반드시 지켜주세요 
- 제출 전 코드가 정상적으로 실행되는지 검토해주세요
- 제출하신 코드에 대해 멘토님의 일부 주관적인 부분점수가 반영될 수 있습니다
- 부분점수 반영 시 상세한 피드백을 드릴 예정이오니, 문의가 있을시 멘토님과 담당 매니저님이 적극 소통할 예정입니다
---
# **4주차 과제**
---

#### 범위

## 3장 고급 선형대수
### 학습 목표
- 벡터와 행렬의 연산이 기하학적으로 어떤 의미인지 이해하고 벡터를 투영분해하며 이를 이용하여 직선의 방정식을 벡터 연산으로 나타낼 수 있다.
- 벡터의 선형독립과 벡터공간의 의미를 이해하고 벡터를 벡터공간에 투영시킬 수 있다. 기저벡터가 바뀌었을 때 이에 해당하게 좌표 변환을 할 수 있다.
- 고윳값 분해의 정의를 알고 행렬의 모양과 고윳값의 관계에 대한 성질을 암기한다.
- 특잇값 분해의 정의를 알고 차원축소문제에 어떻게 응용할 수 있는지 이해한다.

## 4장 심파이(SymPy)로 공부하는 미적분
### 학습목표
- 함수, 역함수의 의미와 함수를 파이썬으로 구현하는 법을 공부한다.
- 함수의 그래프를 그리는 방법과 함수의 기울기를 구하는 방법을 이해한다.
- 데이터 분석에 많이 쓰이는 다양한 함수의 종류와 특징을 알아본다.
- 함수의 미분 공식을 이용하여 함수의 도함수를 구하는 방법을 익힌다.
- 심복릭 연산의 의미를 이해하고 SymPy로 미분과 적분을 하는 방법을 알아본다.
- 부정적분과 정적분을 구별할 수 있다.
- 벡터와 행렬로 이루어진 함수를 미분할 수 있다.
- 범함수의 의미와 범함수의 도함수를 구하는 공식에 대해 알아본다.

## 5장 사이파이(SciPy)로 공부하는 최적화
### 학습 목표
- 최적화 문제의 의미와 풀이법에 대해 공부한다.
- 그리드 서치 방법과 단점에 대해 알아본다.
- 수치적 최적화 방법 중 최급강하법과 뉴튼 방법에 대해 공부한다.
- 라그랑주 승수법과 라그랑주 승수의 의미에 대해 알아본다.
- 부등식 제한조건이 있는 최적화 문제의 KKT 조건에 대해 공부한다.
- 사이파이(SciPy) 패키지를 사용하여 제한조건이 있는 최적화 문제를 풀 수 있다.
- LP 문제와 QP 문제를 이해하고 수식으로 형식화할 수 있다.

---

## 1. (수학_48) 다음 행렬을 고유값과 고유벡터로 대각화하세요. (15점)
$$\mathbf{B} = \begin{bmatrix} 4 & 3 \\ 2 & 1 \end{bmatrix}$$

- 힌트: 고유값(w)과 고유벡터행렬(V)은 np.linalg.eig(), 고유값행렬은 np.diag(), 고유벡터행렬의 역행렬(V_inv)은 np.linalg.inv(), 내적은 @로 구하세요.

\
- 주어진 행렬을 코드로 작성한다. (5점)
- 고유값행렬과 고유벡터행렬, 고유벡터행렬의 역행렬을 구한다. (5점)
- 내적을 통해 결과를 확인한다. (5점)

In [ ]:
# 여기에 코드를 작성해주세요.
import numpy as np
B = np.array([[4,3], [2,1]])
w, V = np.linalg.eig(B)
V_inv = np.linalg.inv(V)
diagB = np.diag(w)

print(f"고유값행렬:\n {diagB}")
print(f"고유벡터행렬:\n {V}")
print(f"고유벡터행렬의 역행렬:\n {V_inv}")
print(f"내적으로 결과 확인: \n {V @ diagB @ V_inv}")

고유값행렬:
 [[ 5.37228132  0.        ]
 [ 0.         -0.37228132]]
고유벡터행렬:
 [[ 0.90937671 -0.56576746]
 [ 0.41597356  0.82456484]]
고유벡터행렬의 역행렬:
 [[ 0.83696501  0.57427572]
 [-0.42222915  0.92305231]]
내적으로 결과 확인: 
 [[4. 3.]
 [2. 1.]]


---

## 2. (수학_52) 펭귄([penguins](https://github.com/allisonhorst/palmerpenguins)) 특징데이터 행렬 X의 분산행렬(COV)을 구하고 이 분산행렬의 고윳값(w)들을 구하세요. (15점)
```
import seaborn as sns
penguins = sns.load_dataset("penguins")
penguins = penguins.dropna().reset_index(drop=True) # 편의상
penguins = penguins[['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']]
X = penguins.to_numpy()
```
- 힌트: 내적은 @, 고유값은 np.linalg.eig()로 구하세요.

\
- 분산행렬을 구한다. (5점)
- 분산행렬의 고윳값들을 구한다. (10점)

In [ ]:
# 여기에 코드를 작성해주세요.
import seaborn as sns
import seaborn as sns
penguins = sns.load_dataset("penguins")
penguins = penguins.dropna().reset_index(drop=True) # 편의상,,
penguins = penguins[['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']]
X = penguins.to_numpy()

#### 코드를 작성해주세요 ####

COV = X.T @ X
w = np.linalg.eig(scatt)
print(f"분산행렬:\n {COV}")
print(f"분산행렬의 고유값들:\n {w[0]}")

분산행렬:
 [[6.54405720e+05 2.50640990e+05 2.96070500e+06 6.24934500e+07]
 [2.50640990e+05 9.94001100e+04 1.14341260e+06 2.37986300e+07]
 [2.96070500e+06 1.14341260e+06 1.35143300e+07 2.84815600e+08]
 [6.24934500e+07 2.37986300e+07 2.84815600e+08 6.10913625e+09]]
분산행렬의 고유값들:
 [6.12314727e+09 2.49884029e+05 5.48277733e+03 1.75066754e+03]


---

## 3. (수학_62, 수학_65) 붓꽃 데이터 중 앞에서 50개의 데이터에 대해 다음 문제를 푸세요. (15점)
```
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA
 
iris = load_iris()
N = 50 # 앞의 50송이만 선택
```

- 문제 1: 4가지 변수(꽃받침 길이와 폭, 꽃잎 길이와 폭)를 모두 사용하여 2차원 PCA를 수행하세요. 
- 문제 2: 문제 1의 결과를 다시 원래의 차원으로 나타내세요.

\
- 4가지 변수를 모두 선택하는 코드를 작성한다. (5점)
- 2차원 PCA를 수행한다. (5점)
- 원래의 차원으로 나타낸다. (5점)

In [ ]:
# 여기에 코드를 작성해주세요.
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA
 
iris = load_iris()
N = 50 
X = iris.data[:N, :4]               #4가지 변수를 모두 선택 

#2차원 PCA 수행 
pca1 = PCA(n_components = 2)
X_low = pca1.fit_transform(X)
print(f"2차원 근사 행렬:\n {X_low}\n")

#원래의 차원으로 나타내기
X2 = pca1.inverse_transform(X_low)
print(f"원래의 차원으로 복귀한 행렬:\n {X2}")

---

## 4. (수학_84) 다음 함수에 대한 1차/ 2차 편미분을 SymPy를 사용하여 구하세요. (15점)

$$ f(x, y) = exp(x^3 - 2y^2) $$

- 문제 1: 주어진 함수를 SymPy로 정의하세요. (5점)
  - 힌트: 심볼 변수 정의는 symbols()로 구하세요.
- 문제 2: $ f_y, f_{yx} $ 를 각각 구하세요. (10점)
  - 힌트: 미분은 diff()으로 구하세요.

In [ ]:
# 여기에 코드를 작성해주세요.
import sympy
sympy.init_printing(use_latex='mathjax')
x, y  = sympy.symbols('x y')
f = sympy.exp(x**3 - 2*y**2)    
f_y = sympy.diff(f, y)
f_yx = sympy.diff(f, y, x)
f, f_y, f_yx

⎛  3      2         3      2             3      2⎞
⎜ x  - 2⋅y         x  - 2⋅y        2    x  - 2⋅y ⎟
⎝ℯ         , -4⋅y⋅ℯ         , -12⋅x ⋅y⋅ℯ         ⎠

---

## 5. (수학_87) 다음 정적분의 값을 부정적분과 수치적분 두 가지 방법으로 구하세요. (20점)
$$ \int_0^4 (x^2 + 3exp(x)) dx  $$

- 문제 1: SymPy를 사용하여 부정적분 방법으로 구하세요. (10점)
  - 힌트: 심볼 변수 정의는 symbols()로 구하세요.
- 문제 2: 수치적분 방법으로 구하세요. (10점)
  - 힌트: 수치적분은 sp.integrate.quad()로 구하세요.

In [ ]:
# 여기에 코드를 작성해주세요.
import scipy as sp
import sympy
sympy.init_printing(use_latex='mathjax')
x  = sympy.symbols('x')
f = x**2 + 3*sympy.exp(x)

#부정 적분
F = sympy.integrate(f)
defi = (F.subs(x,4) - F.subs(x,0)).evalf()

#수치 적분 
def f1(x):
  return x**2 + 3*sympy.exp(x)
indef = sp.integrate.quad(f1, 0, 4)[0] 

print(f"부정 적분 결과:\n {defi}")
print(f"수치 적분 결과:\n {indef}")

(182.127783432766, 182.12778343276605)

(182.12778343276605, 2.02202458591001e-12)

---

## 6. (수학_97, 수학_98) 다음 함수를 최적화하세요. (20점)

$$ f_2(x, y) = (1 - x)^2 + 100(y - x^2)^2 $$


- 문제: 그레디언트벡터 함수를 구현하여 jac 인수로 주는 방법으로 계산 속도를 향상시키세요.
  - 조건: 초깃값 x0 = (2, 0.3)
  - 힌트: 최적화는 sp.optimize.minimize()로 구하세요.

In [ ]:
# 여기에 코드를 작성해주세요.
import scipy as sp
import numpy as np
import scipy.optimize
def f1(x):
  return (1-x[0])**2 + 100*(x[1]-x[0]**2)**2

def fj(x):
  return np.array((-400*x[0]*(-x[0]**2 + x[1])+2*x[0]-2, -200*x[0]**2+200*x[1]))

x0 = (2, 0.3)
result = sp.optimize.minimize(f1, x0, jac = fj)
print(result)

      fun: 1.0392868446638963e-14
 hess_inv: array([[0.49022342, 0.98027934],
       [0.98027934, 1.96521752]])
      jac: array([ 1.58870154e-06, -8.86163974e-07])
  message: 'Optimization terminated successfully.'
     nfev: 25
      nit: 18
     njev: 25
   status: 0
  success: True
        x: array([0.99999991, 0.99999981])
