---
#### 제로베이스(https://zero-base.co.kr/)
#### 데이터사이언스 90일 완주반 
---
#### **Guideline**
- 총점 100점으로 주차별로 약 2~3개 문제가 제시됩니다
- 각 문제마다 안내사항과 요구사항을 꼼꼼하게 확인해주신 후, 코드를 작성해주세요 
- 코드는 제시드리는 결과만 같게 나온다면, 추후 모범답안으로 드리는 코드와 달라도 괜찮습니다 

#### **Notice!** 
- 제출 기한을 반드시 지켜주세요 
- 제출 전 코드가 정상적으로 실행되는지 검토해주세요
- 제출하신 코드에 대해 멘토님의 일부 주관적인 부분점수가 반영될 수 있습니다
- 부분점수 반영 시 상세한 피드백을 드릴 예정이오니, 문의가 있을시 멘토님과 담당 매니저님이 적극 소통할 예정입니다
---
# **3주차 과제**
- 총 100점 4문제
- 각 25점
---

## 1. (수학_21, 수학_22) 다음 행렬의 대각합과 행렬식을 구하세요. (25점)
- 조건: print문을 이용하여 대각합(trace)과 행렬식(det)을 출력하세요.

$$\mathbf{A} = \begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \end{bmatrix}$$

- 힌트: 행렬의 대각합은 np.trace(A), 행렬식은 np.linalg.det(A)로 구하세요.

\
- 주어진 행렬을 코드로 작성한다. (5점)
- 행렬의 대각합을 구한다. (10점)
- 행렬의 행렬식을 구한다. (10점)

In [ ]:
# 여기에 코드를 작성해주세요.
import numpy as np
mat = np.array([[1,2,1],[3,0,1],[0,2,4]])
print(f"대각합: {np.trace(mat)}")
print(f"행렬식: {np.linalg.det(mat)}")

대각합: 5
행렬식: -19.999999999999996


---

## 2. (수학_25, 수학_27, 수학_28) 다음과 같은 선형 연립방정식을 Numpy를 사용하여 최소자승문제의 해를 구하세요. (25점)

```
  𝑥₁ +  𝑥₂      = 3
  𝑥₁ +  𝑥₂ + 𝑥₃ = 3.6
  𝑥₁       + 𝑥₃ = 2.5
  𝑥₁ + 2𝑥₂ + 𝑥₃ = 4.4
```
- 문제 1: 의사역행렬( ***(AᵀA)⁻¹Aᵀ*** )을 직접 계산하여 해를 구하세요.
  - 힌트: 역행렬은 np.linalg.inv()로 구하세요. 
- 문제 2: lstsq() 명령을 사용하여 해를 구하세요(문제 1의 결과와 비교해보세요).

\
- 주어진 방정식을 코드로 작성한다. (5점)
- 행렬A의 의사역행렬을 구한다. (10점)
- 최소자승문제의 해를 구한다. (10점)

In [ ]:
# 여기에 코드를 작성해주세요.
#### 문제 1
import numpy as np
b = np.array([[3], [3.6], [2.5], [4.4]])
A = np.array([[1, 2, 0], [1, 1, 1], [1, 0, 1], [1, 2, 1]])
Doct = np.linalg.inv(A.T @ A)@A.T
print(f"의사역행렬: {Doct}\n")
print(f"해: {Doct@b}")

의사역행렬: [[ 1.00000000e+00  6.66133815e-16  1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00 -1.66533454e-16 -5.00000000e-01  5.00000000e-01]
 [-1.00000000e+00  3.33333333e-01 -1.66666667e-01  8.33333333e-01]]

해: [[1.1 ]
 [0.95]
 [1.45]]


In [ ]:
# 여기에 코드를 작성해주세요.
#### 문제 2
import numpy as np
A = np.array([[1, 2, 0], [1, 1, 1], [1, 0, 1], [1, 2, 1]])
v = np.array([[3], [3.6], [2.5], [4.4]])
x, red, rank, s = np.linalg.lstsq(A, v)
print(f"해: {x}")

해: [[1.1 ]
 [0.95]
 [1.45]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


In [ ]:
# 여기에 코드를 작성해주세요.
import numpy as np
b = np.array([[3], [3.6], [2.5], [4.4]])
A = np.array([[1, 2, 0], [1, 1, 1], [1, 0, 1], [1, 2, 1]])
Doct = np.linalg.inv(A.T @ A)@A.T
x, red, rank, s = np.linalg.lstsq(A, v)

print(f"의사역행렬: {Doct}\n")
print(f"의사역행렬을 이용한 해: {Doct@b}\n")
print(f"최소자승문제의 해: {x}\n")

의사역행렬: [[ 1.00000000e+00  6.66133815e-16  1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00 -1.66533454e-16 -5.00000000e-01  5.00000000e-01]
 [-1.00000000e+00  3.33333333e-01 -1.66666667e-01  8.33333333e-01]]

의사역행렬을 이용한 해: [[1.1 ]
 [0.95]
 [1.45]]

최소자승문제의 해: [[1.1 ]
 [0.95]
 [1.45]]



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


---

## 3. (수학_33) 벡터로 표현된 데이터 a와 b 사이의 유클리드 거리와 코사인 유사도, 그리고 코사인 거리를 구하세요. (25점)
- 조건 : print문을 이용하여 코사인 유사도 cosine_similarity와 코사인 거리 cosine_distance를 출력하세요.

$$\mathbf{a} = \begin{bmatrix} 4 \\ 0 \\ 2 \\ 7 \end{bmatrix}$$
&nbsp;
$$\mathbf{b} = \begin{bmatrix} 1 \\ -2 \\ 4 \\ 0 \end{bmatrix}$$

- 힌트: 벡터의 norm은 np.linalg.norm(), 두 벡터의 내적은 np.dot()로 구하세요.

\
- 주어진 벡터를 코드로 작성한다. (5점)
- 유클리드 거리를 구한다. (6점)
- 코사인 유사도를 구한다. (7점)
- 코사인 거리를 구한다. (6점)

In [ ]:
# 여기에 코드를 작성해주세요.
import numpy as np
a = np.array([[4], [0], [2], [7]])
b = np.array([[1], [-2], [4], [0]])

# 벡터를 2차원 배열로 해도 되나요? 
euclidean_distance = np.linalg.norm(a - b)
cosine_similarity = ((np.dot(a.T, b))/ (np.linalg.norm(a)*np.linalg.norm(b))).flatten()
cosine_distance = 1 - cosine_similarity

print(f"유클리드 거리:", euclidean_distance)
print(f"코사인 유사도:", cosine_similarity)
print(f"코사인 거리:", cosine_distance)

유클리드 거리: 8.12403840463596
코사인 유사도: [0.31524416]
코사인 거리: [0.68475584]


In [ ]:
# 여기에 코드를 작성해주세요.
# 위의 답과 중복
import numpy as np
a = np.array([[4], [0], [2], [7]])
b = np.array([[1], [-2], [4], [0]])

euclidean_distance = np.linalg.norm(a - b)
cosine_similarity = ((np.dot(a.T, b))/ (np.linalg.norm(a)*np.linalg.norm(b))).flatten()
cosine_distance = 1 - cosine_similarity

print(f"유클리드 거리:", euclidean_distance)
print(f"코사인 유사도:", cosine_similarity)
print(f"코사인 거리:", cosine_distance)

[1. 0.]
[0. 2.]


In [ ]:
# 여기에 코드를 작성해주세요.
# 위의 답과 중복
import numpy as np
a = np.array([[4], [0], [2], [7]])
b = np.array([[1], [-2], [4], [0]])

euclidean_distance = np.linalg.norm(a - b)
cosine_similarity = ((np.dot(a.T, b))/ (np.linalg.norm(a)*np.linalg.norm(b))).flatten()
cosine_distance = 1 - cosine_similarity

print(f"유클리드 거리:", euclidean_distance)
print(f"코사인 유사도:", cosine_similarity)
print(f"코사인 거리:", cosine_distance)

[[2 0]
 [0 2]]
2


---

## 4. (수학_40) 다음 두 개의 벡터로 랭크-2 행렬(m2)을 만들고, Numpy로 랭크를 계산하여 실제로 2가 나오는지 확인하세요. (25점)

- 조건 : print문을 이용하여 랭크-2 행렬 m2과 실제 랭크 rank를 출력하세요.

$$\mathbf{x_1} = \begin{bmatrix} 1 \\ 1 \end{bmatrix}, \mathbf{x_2} = \begin{bmatrix} 1 \\ -1 \end{bmatrix}$$

- 힌트: 두 벡터의 내적은 @, 행렬의 랭크 계산은 np.linalg.matrix_rank()로 구하세요.

\
- 주어진 벡터를 코드로 작성한다.(5점)
- 주어진 벡터로 랭크-2 행렬을 만든다. (10점)
- 실제 랭크를 확인한다. (10점)

In [ ]:
# 여기에 코드를 작성해주세요.
import numpy as np
x1 = np.array([[1], [1]])
x2 = np.array(([1], [-1]))

m2 = x1@x1.T + x2@x2.T
rank = np.linalg.matrix_rank(m2)

print(m2)
print(rank)

[[2 0]
 [0 2]]
2
